# tasks file for haproxy
---

- name: force gathering facts which will be needed by the role when a previous global fact gathering has not yet been done
  setup:
    gather_subset:
      - 'all_ipv4_addresses'
      - 'all_ipv6_addresses'
      - 'distribution'
      - 'distribution_major_version'
      - 'distribution_release'
      - 'distribution_version'
      - 'dns'
      - 'os_family'
      - 'python'
      - 'python_version'
  when: ansible_os_family is not defined
  tags:
    - configuration
    - haproxy
    - haproxy-install

- name: check version support
  fail:
    msg: "HAProxy version {{ haproxy_version }} is not supported"
  when: haproxy_version | string not in haproxy_versions_supported
  tags:
    - configuration
    - haproxy
    - haproxy-check-version-support

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - configuration
    - haproxy
    - haproxy-install

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'
  tags:
    - configuration
    - haproxy
    - haproxy-install

#- include: install.yml
#  tags:
#    - configuration
#    - haproxy
#    - haproxy-install

- include: certificates.yml
  tags:
    - configuration
    - haproxy
    - haproxy-certificates

- include: acl.yml
  tags:
    - configuration
    - haproxy
    - haproxy-acl

- include: configuration.yml
  tags:
    - configuration
    - haproxy
    - haproxy-configuration

- name: start and enable service
  service:
    name: haproxy
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - configuration
    - haproxy
    - haproxy-start-enable-service
